<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
    name: notificationservice
spec:
    type: ClusterIP
    ports:
    - port: 3005 
    selector:
=======
apiVersion: v1
kind: Service
metadata:
    name: notificationservice
spec:
    type: ClusterIP
    ports:
    - port: 3005 
    selector:
>>>>>>> 6b8594a2b93fd94b700bb954f1ea13bdbc1e30d5
        app: notificationservice